
export const cities = [
    { id: 1, name: 'Adana' },
    { id: 2, name: 'Adıyaman' },
    { id: 3, name: 'Afyonkarahisar' },
    { id: 4, name: 'Ağrı' },
    { id: 5, name: 'Amasya' },
    { id: 6, name: 'Ankara' },
    { id: 7, name: 'Antalya' },
    { id: 8, name: 'Artvin' },
    { id: 9, name: 'Aydın' },
    { id: 10, name: 'Balıkesir' },
    { id: 11, name: 'Bilecik' },
    { id: 12, name: 'Bingöl' },
    { id: 13, name: 'Bitlis' },
    { id: 14, name: 'Bolu' },
    { id: 15, name: 'Burdur' },
    { id: 16, name: 'Bursa' },
    { id: 17, name: 'Çanakkale' },
    { id: 18, name: 'Çankırı' },
    { id: 19, name: 'Çorum' },
    { id: 20, name: 'Denizli' },
    { id: 21, name: 'Diyarbakır' },
    { id: 22, name: 'Edirne' },
    { id: 23, name: 'Elazığ' },
    { id: 24, name: 'Erzincan' },
    { id: 25, name: 'Erzurum' },
    { id: 26, name: 'Eskişehir' },
    { id: 27, name: 'Gaziantep' },
    { id: 28, name: 'Giresun' },
    { id: 29, name: 'Gümüşhane' },
    { id: 30, name: 'Hakkari' },
    { id: 31, name: 'Hatay' },
    { id: 32, name: 'Isparta' },
    { id: 33, name: 'Mersin' },
    { id: 34, name: 'İstanbul' },
    { id: 35, name: 'İzmir' },
    { id: 36, name: 'Kars' },
    { id: 37, name: 'Kastamonu' },
    { id: 38, name: 'Kayseri' },
    { id: 39, name: 'Kırklareli' },
    { id: 40, name: 'Kırşehir' },
    { id: 41, name: 'Kocaeli' },
    { id: 42, name: 'Konya' },
    { id: 43, name: 'Kütahya' },
    { id: 44, name: 'Malatya' },
    { id: 45, name: 'Manisa' },
    { id: 46, name: 'Kahramanmaraş' },
    { id: 47, name: 'Mardin' },
    { id: 48, name: 'Muğla' },
    { id: 49, name: 'Muş' },
    { id: 50, name: 'Nevşehir' },
    { id: 51, name: 'Niğde' },
    { id: 52, name: 'Ordu' },
    { id: 53, name: 'Rize' },
    { id: 54, name: 'Sakarya' },
    { id: 55, name: 'Samsun' },
    { id: 56, name: 'Siirt' },
    { id: 57, name: 'Sinop' },
    { id: 58, name: 'Sivas' },
    { id: 59, name: 'Tekirdağ' },
    { id: 60, name: 'Tokat' },
    { id: 61, name: 'Trabzon' },
    { id: 62, name: 'Tunceli' },
    { id: 63, name: 'Şanlıurfa' },
    { id: 64, name: 'Uşak' },
    { id: 65, name: 'Van' },
    { id: 66, name: 'Yozgat' },
    { id: 67, name: 'Zonguldak' },
    { id: 68, name: 'Aksaray' },
    { id: 69, name: 'Bayburt' },
    { id: 70, name: 'Karaman' },
    { id: 71, name: 'Kırıkkale' },
    { id: 72, name: 'Batman' },
    { id: 73, name: 'Şırnak' },
    { id: 74, name: 'Bartın' },
    { id: 75, name: 'Ardahan' },
    { id: 76, name: 'Iğdır' },
    { id: 77, name: 'Yalova' },
    { id: 78, name: 'Karabük' },
    { id: 79, name: 'Kilis' },
    { id: 80, name: 'Osmaniye' },
    { id: 81, name: 'Düzce' }
];

export const districts: { [key: number]: { id: number, name: string }[] } = {
    1: [
        { id: 1, name: 'Aladağ' },
        { id: 2, name: 'Ceyhan' },
        { id: 3, name: 'Çukurova' },
        { id: 4, name: 'Feke' },
        { id: 5, name: 'İmamoğlu' },
        { id: 6, name: 'Karaisalı' },
        { id: 7, name: 'Karataş' },
        { id: 8, name: 'Kozan' },
        { id: 9, name: 'Pozantı' },
        { id: 10, name: 'Saimbeyli' },
        { id: 11, name: 'Sarıçam' },
        { id: 12, name: 'Seyhan' },
        { id: 13, name: 'Tufanbeyli' },
        { id: 14, name: 'Yumurtalık' },
        { id: 15, name: 'Yüreğir' }
    ],
    2: [
        { id: 16, name: 'Besni' },
        { id: 17, name: 'Çelikhan' },
        { id: 18, name: 'Gerger' },
        { id: 19, name: 'Gölbaşı' },
        { id: 20, name: 'Kahta' },
        { id: 21, name: 'Merkez' },
        { id: 22, name: 'Samsat' },
        { id: 23, name: 'Sincik' },
        { id: 24, name: 'Tut' }
    ],
    3: [
        { id: 25, name: 'Başmakçı' },
        { id: 26, name: 'Bayat' },
        { id: 27, name: 'Bolvadin' },
        { id: 28, name: 'Çay' },
        { id: 29, name: 'Çobanlar' },
        { id: 30, name: 'Dazkırı' },
        { id: 31, name: 'Dinar' },
        { id: 32, name: 'Emirdağ' },
        { id: 33, name: 'Evciler' },
        { id: 34, name: 'Hocalar' },
        { id: 35, name: 'İhsaniye' },
        { id: 36, name: 'İscehisar' },
        { id: 37, name: 'Merkez' },
        { id: 38, name: 'Sandıklı' },
        { id: 39, name: 'Sinanpaşa' },
        { id: 40, name: 'Sultandağı' },
        { id: 41, name: 'Şuhut' }
    ],
    4: [
        { id: 42, name: 'Diyadin' },
        { id: 43, name: 'Doğubayazıt' },
        { id: 44, name: 'Eleşkirt' },
        { id: 45, name: 'Hamur' },
        { id: 46, name: 'Merkez' },
        { id: 47, name: 'Patnos' },
        { id: 48, name: 'Taşlıçay' },
        { id: 49, name: 'Tutak' }
    ],
    5: [
        { id: 50, name: 'Göynücek' },
        { id: 51, name: 'Gümüşhacıköy' },
        { id: 52, name: 'Hamamözü' },
        { id: 53, name: 'Merkez' },
        { id: 54, name: 'Merzifon' },
        { id: 55, name: 'Suluova' },
        { id: 56, name: 'Taşova' }
    ],
    6: [
        { id: 57, name: 'Akyurt' },
        { id: 58, name: 'Altındağ' },
        { id: 59, name: 'Ayaş' },
        { id: 60, name: 'Bala' },
        { id: 61, name: 'Beypazarı' },
        { id: 62, name: 'Çamlıdere' },
        { id: 63, name: 'Çankaya' },
        { id: 64, name: 'Çubuk' },
        { id: 65, name: 'Elmadağ' },
        { id: 66, name: 'Etimesgut' },
        { id: 67, name: 'Evren' },
        { id: 68, name: 'Gölbaşı' },
        { id: 69, name: 'Güdül' },
        { id: 70, name: 'Haymana' },
        { id: 71, name: 'Kahramankazan' },
        { id: 72, name: 'Kalecik' },
        { id: 73, name: 'Keçiören' },
        { id: 74, name: 'Kızılcahamam' },
        { id: 75, name: 'Mamak' },
        { id: 76, name: 'Nallıhan' },
        { id: 77, name: 'Polatlı' },
        { id: 78, name: 'Pursaklar' },
        { id: 79, name: 'Sincan' },
        { id: 80, name: 'Şereflikoçhisar' },
        { id: 81, name: 'Yenimahalle' }
    ],
    7: [
        { id: 82, name: 'Akseki' },
        { id: 83, name: 'Aksu' },
        { id: 84, name: 'Alanya' },
        { id: 85, name: 'Demre' },
        { id: 86, name: 'Döşemealtı' },
        { id: 87, name: 'Elmalı' },
        { id: 88, name: 'Finike' },
        { id: 89, name: 'Gazipaşa' },
        { id: 90, name: 'Gündoğmuş' },
        { id: 91, name: 'İbradı' },
        { id: 92, name: 'Kaş' },
        { id: 93, name: 'Kemer' },
        { id: 94, name: 'Kepez' },
        { id: 95, name: 'Konyaaltı' },
        { id: 96, name: 'Korkuteli' },
        { id: 97, name: 'Kumluca' },
        { id: 98, name: 'Manavgat' },
        { id: 99, name: 'Muratpaşa' },
        { id: 100, name: 'Serik' }
    ],
    8: [
        { id: 101, name: 'Ardanuç' },
        { id: 102, name: 'Arhavi' },
        { id: 103, name: 'Borçka' },
        { id: 104, name: 'Hopa' },
        { id: 105, name: 'Kemalpaşa' },
        { id: 106, name: 'Merkez' },
        { id: 107, name: 'Murgul' },
        { id: 108, name: 'Şavşat' },
        { id: 109, name: 'Yusufeli' }
    ],
    9: [
        { id: 110, name: 'Bozdoğan' },
        { id: 111, name: 'Buharkent' },
        { id: 112, name: 'Çine' },
        { id: 113, name: 'Didim' },
        { id: 114, name: 'Efeler' },
        { id: 115, name: 'Germencik' },
        { id: 116, name: 'İncirliova' },
        { id: 117, name: 'Karacasu' },
        { id: 118, name: 'Karpuzlu' },
        { id: 119, name: 'Koçarlı' },
        { id: 120, name: 'Köşk' },
        { id: 121, name: 'Kuşadası' },
        { id: 122, name: 'Kuyucak' },
        { id: 123, name: 'Nazilli' },
        { id: 124, name: 'Söke' },
        { id: 125, name: 'Sultanhisar' },
        { id: 126, name: 'Yenipazar' }
    ],
    10: [
        { id: 127, name: 'Altıeylül' },
        { id: 128, name: 'Ayvalık' },
        { id: 129, name: 'Balya' },
        { id: 130, name: 'Bandırma' },
        { id: 131, name: 'Bigadiç' },
        { id: 132, name: 'Burhaniye' },
        { id: 133, name: 'Dursunbey' },
        { id: 134, name: 'Edremit' },
        { id: 135, name: 'Erdek' },
        { id: 136, name: 'Gömeç' },
        { id: 137, name: 'Gönen' },
        { id: 138, name: 'Havran' },
        { id: 139, name: 'İvrindi' },
        { id: 140, name: 'Karesi' },
        { id: 141, name: 'Kepsut' },
        { id: 142, name: 'Manyas' },
        { id: 143, name: 'Marmara' },
        { id: 144, name: 'Savaştepe' },
        { id: 145, name: 'Sındırgı' },
        { id: 146, name: 'Susurluk' }
    ],
    11: [
        { id: 147, name: 'Bozüyük' },
        { id: 148, name: 'Gölpazarı' },
        { id: 149, name: 'İnhisar' },
        { id: 150, name: 'Merkez' },
        { id: 151, name: 'Osmaneli' },
        { id: 152, name: 'Pazaryeri' },
        { id: 153, name: 'Söğüt' },
        { id: 154, name: 'Yenipazar' }
    ],
    12: [
        { id: 155, name: 'Adaklı' },
        { id: 156, name: 'Genç' },
        { id: 157, name: 'Karlıova' },
        { id: 158, name: 'Kiğı' },
        { id: 159, name: 'Merkez' },
        { id: 160, name: 'Solhan' },
        { id: 161, name: 'Yayladere' },
        { id: 162, name: 'Yedisu' }
    ],
    13: [
        { id: 163, name: 'Adilcevaz' },
        { id: 164, name: 'Ahlat' },
        { id: 165, name: 'Güroymak' },
        { id: 166, name: 'Hizan' },
        { id: 167, name: 'Merkez' },
        { id: 168, name: 'Mutki' },
        { id: 169, name: 'Tatvan' }
    ],
    14: [
        { id: 170, name: 'Dörtdivan' },
        { id: 171, name: 'Gerede' },
        { id: 172, name: 'Göynük' },
        { id: 173, name: 'Kıbrıscık' },
        { id: 174, name: 'Mengen' },
        { id: 175, name: 'Merkez' },
        { id: 176, name: 'Mudurnu' },
        { id: 177, name: 'Seben' },
        { id: 178, name: 'Yeniçağa' }
    ],
    15: [
        { id: 179, name: 'Ağlasun' },
        { id: 180, name: 'Altınyayla' },
        { id: 181, name: 'Bucak' },
        { id: 182, name: 'Çavdır' },
        { id: 183, name: 'Çeltikçi' },
        { id: 184, name: 'Gölhisar' },
        { id: 185, name: 'Karamanlı' },
        { id: 186, name: 'Kemer' },
        { id: 187, name: 'Merkez' },
        { id: 188, name: 'Tefenni' },
        { id: 189, name: 'Yeşilova' }
    ],
    16: [
        { id: 190, name: 'Büyükorhan' },
        { id: 191, name: 'Gemlik' },
        { id: 192, name: 'Gürsu' },
        { id: 193, name: 'Harmancık' },
        { id: 194, name: 'İnegöl' },
        { id: 195, name: 'İznik' },
        { id: 196, name: 'Karacabey' },
        { id: 197, name: 'Keles' },
        { id: 198, name: 'Kestel' },
        { id: 199, name: 'Mudanya' },
        { id: 200, name: 'Mustafakemalpaşa' },
        { id: 201, name: 'Nilüfer' },
        { id: 202, name: 'Orhaneli' },
        { id: 203, name: 'Orhangazi' },
        { id: 204, name: 'Osmangazi' },
        { id: 205, name: 'Yenişehir' },
        { id: 206, name: 'Yıldırım' }
    ],
    17: [
        { id: 207, name: 'Ayvacık' },
        { id: 208, name: 'Bayramiç' },
        { id: 209, name: 'Biga' },
        { id: 210, name: 'Bozcaada' },
        { id: 211, name: 'Çan' },
        { id: 212, name: 'Eceabat' },
        { id: 213, name: 'Ezine' },
        { id: 214, name: 'Gelibolu' },
        { id: 215, name: 'Gökçeada' },
        { id: 216, name: 'Lapseki' },
        { id: 217, name: 'Merkez' },
        { id: 218, name: 'Yenice' }
    ],
    18: [
        { id: 219, name: 'Atkaracalar' },
        { id: 220, name: 'Bayramören' },
        { id: 221, name: 'Çerkeş' },
        { id: 222, name: 'Eldivan' },
        { id: 223, name: 'Ilgaz' },
        { id: 224, name: 'Kızılırmak' },
        { id: 225, name: 'Korgun' },
        { id: 226, name: 'Kurşunlu' },
        { id: 227, name: 'Merkez' },
        { id: 228, name: 'Orta' },
        { id: 229, name: 'Şabanözü' },
        { id: 230, name: 'Yapraklı' }
    ],
    19: [
        { id: 231, name: 'Alaca' },
        { id: 232, name: 'Bayat' },
        { id: 233, name: 'Boğazkale' },
        { id: 234, name: 'Dodurga' },
        { id: 235, name: 'İskilip' },
        { id: 236, name: 'Kargı' },
        { id: 237, name: 'Laçin' },
        { id: 238, name: 'Mecitözü' },
        { id: 239, name: 'Merkez' },
        { id: 240, name: 'Oğuzlar' },
        { id: 241, name: 'Ortaköy' },
        { id: 242, name: 'Osmancık' },
        { id: 243, name: 'Sungurlu' },
        { id: 244, name: 'Uğurludağ' }
    ],
    20: [
        { id: 245, name: 'Acıpayam' },
        { id: 246, name: 'Babadağ' },
        { id: 247, name: 'Baklan' },
        { id: 248, name: 'Bekilli' },
        { id: 249, name: 'Beyağaç' },
        { id: 250, name: 'Bozkurt' },
        { id: 251, name: 'Buldan' },
        { id: 252, name: 'Çal' },
        { id: 253, name: 'Çameli' },
        { id: 254, name: 'Çardak' },
        { id: 255, name: 'Çivril' },
        { id: 256, name: 'Güney' },
        { id: 257, name: 'Honaz' },
        { id: 258, name: 'Kale' },
        { id: 259, name: 'Merkezefendi' },
        { id: 260, name: 'Pamukkale' },
        { id: 261, name: 'Sarayköy' },
        { id: 262, name: 'Serinhisar' },
        { id: 263, name: 'Tavas' }
    ],
    21: [
        { id: 264, name: 'Bağlar' },
        { id: 265, name: 'Bismil' },
        { id: 266, name: 'Çermik' },
        { id: 267, name: 'Çınar' },
        { id: 268, name: 'Çüngüş' },
        { id: 269, name: 'Dicle' },
        { id: 270, name: 'Eğil' },
        { id: 271, name: 'Ergani' },
        { id: 272, name: 'Hani' },
        { id: 273, name: 'Hazro' },
        { id: 274, name: 'Kayapınar' },
        { id: 275, name: 'Kocaköy' },
        { id: 276, name: 'Kulp' },
        { id: 277, name: 'Lice' },
        { id: 278, name: 'Silvan' },
        { id: 279, name: 'Sur' },
        { id: 280, name: 'Yenişehir' }
    ],
    22: [
        { id: 281, name: 'Enez' },
        { id: 282, name: 'Havsa' },
        { id: 283, name: 'İpsala' },
        { id: 284, name: 'Keşan' },
        { id: 285, name: 'Lalapaşa' },
        { id: 286, name: 'Meriç' },
        { id: 287, name: 'Merkez' },
        { id: 288, name: 'Süloğlu' },
        { id: 289, name: 'Uzunköprü' }
    ],
    23: [
        { id: 290, name: 'Ağın' },
        { id: 291, name: 'Alacakaya' },
        { id: 292, name: 'Arıcak' },
        { id: 293, name: 'Baskil' },
        { id: 294, name: 'Karakoçan' },
        { id: 295, name: 'Keban' },
        { id: 296, name: 'Kovancılar' },
        { id: 297, name: 'Maden' },
        { id: 298, name: 'Merkez' },
        { id: 299, name: 'Palu' },
        { id: 300, name: 'Sivrice' }
    ],
    24: [
        { id: 301, name: 'Çayırlı' },
        { id: 302, name: 'İliç' },
        { id: 303, name: 'Kemah' },
        { id: 304, name: 'Kemaliye' },
        { id: 305, name: 'Merkez' },
        { id: 306, name: 'Otlukbeli' },
        { id: 307, name: 'Refahiye' },
        { id: 308, name: 'Tercan' },
        { id: 309, name: 'Üzümlü' }
    ],
    25: [
        { id: 310, name: 'Aşkale' },
        { id: 311, name: 'Aziziye' },
        { id: 312, name: 'Çat' },
        { id: 313, name: 'Hınıs' },
        { id: 314, name: 'Horasan' },
        { id: 315, name: 'İspir' },
        { id: 316, name: 'Karaçoban' },
        { id: 317, name: 'Karayazı' },
        { id: 318, name: 'Köprüköy' },
        { id: 319, name: 'Narman' },
        { id: 320, name: 'Oltu' },
        { id: 321, name: 'Olur' },
        { id: 322, name: 'Palandöken' },
        { id: 323, name: 'Pasinler' },
        { id: 324, name: 'Pazaryolu' },
        { id: 325, name: 'Şenkaya' },
        { id: 326, name: 'Tekman' },
        { id: 327, name: 'Tortum' },
        { id: 328, name: 'Uzundere' },
        { id: 329, name: 'Yakutiye' }
    ],
    26: [
        { id: 330, name: 'Alpu' },
        { id: 331, name: 'Beylikova' },
        { id: 332, name: 'Çifteler' },
        { id: 333, name: 'Günyüzü' },
        { id: 334, name: 'Han' },
        { id: 335, name: 'İnönü' },
        { id: 336, name: 'Mahmudiye' },
        { id: 337, name: 'Mihalgazi' },
        { id: 338, name: 'Mihalıççık' },
        { id: 339, name: 'Odunpazarı' },
        { id: 340, name: 'Sarıcakaya' },
        { id: 341, name: 'Seyitgazi' },
        { id: 342, name: 'Sivrihisar' },
        { id: 343, name: 'Tepebaşı' }
    ],
    27: [
        { id: 344, name: 'Araban' },
        { id: 345, name: 'İslahiye' },
        { id: 346, name: 'Karkamış' },
        { id: 347, name: 'Nizip' },
        { id: 348, name: 'Nurdağı' },
        { id: 349, name: 'Oğuzeli' },
        { id: 350, name: 'Şahinbey' },
        { id: 351, name: 'Şehitkamil' },
        { id: 352, name: 'Yavuzeli' }
    ],
    28: [
        { id: 353, name: 'Alucra' },
        { id: 354, name: 'Bulancak' },
        { id: 355, name: 'Çamoluk' },
        { id: 356, name: 'Çanakçı' },
        { id: 357, name: 'Dereli' },
        { id: 358, name: 'Doğankent' },
        { id: 359, name: 'Espiye' },
        { id: 360, name: 'Eynesil' },
        { id: 361, name: 'Görele' },
        { id: 362, name: 'Güce' },
        { id: 363, name: 'Keşap' },
        { id: 364, name: 'Merkez' },
        { id: 365, name: 'Piraziz' },
        { id: 366, name: 'Şebinkarahisar' },
        { id: 367, name: 'Tirebolu' },
        { id: 368, name: 'Yağlıdere' }
    ],
    29: [
        { id: 369, name: 'Kelkit' },
        { id: 370, name: 'Köse' },
        { id: 371, name: 'Kürtün' },
        { id: 372, name: 'Merkez' },
        { id: 373, name: 'Şiran' },
        { id: 374, name: 'Torul' }
    ],
    30: [
        { id: 375, name: 'Çukurca' },
        { id: 376, name: 'Derecik' },
        { id: 377, name: 'Merkez' },
        { id: 378, name: 'Şemdinli' },
        { id: 379, name: 'Yüksekova' }
    ],
    31: [
        { id: 380, name: 'Altınözü' },
        { id: 381, name: 'Antakya' },
        { id: 382, name: 'Arsuz' },
        { id: 383, name: 'Belen' },
        { id: 384, name: 'Defne' },
        { id: 385, name: 'Dörtyol' },
        { id: 386, name: 'Erzin' },
        { id: 387, name: 'Hassa' },
        { id: 388, name: 'İskenderun' },
        { id: 389, name: 'Kırıkhan' },
        { id: 390, name: 'Kumlu' },
        { id: 391, name: 'Payas' },
        { id: 392, name: 'Reyhanlı' },
        { id: 393, name: 'Samandağ' },
        { id: 394, name: 'Yayladağı' }
    ],
    32: [
        { id: 395, name: 'Aksu' },
        { id: 396, name: 'Atabey' },
        { id: 397, name: 'Eğirdir' },
        { id: 398, name: 'Gelendost' },
        { id: 399, name: 'Gönen' },
        { id: 400, name: 'Keçiborlu' },
        { id: 401, name: 'Merkez' },
        { id: 402, name: 'Senirkent' },
        { id: 403, name: 'Sütçüler' },
        { id: 404, name: 'Şarkikaraağaç' },
        { id: 405, name: 'Uluborlu' },
        { id: 406, name: 'Yalvaç' },
        { id: 407, name: 'Yenişarbademli' }
    ],
    33: [
        { id: 408, name: 'Akdeniz' },
        { id: 409, name: 'Anamur' },
        { id: 410, name: 'Aydıncık' },
        { id: 411, name: 'Bozyazı' },
        { id: 412, name: 'Çamlıyayla' },
        { id: 413, name: 'Erdemli' },
        { id: 414, name: 'Gülnar' },
        { id: 415, name: 'Mezitli' },
        { id: 416, name: 'Mut' },
        { id: 417, name: 'Silifke' },
        { id: 418, name: 'Tarsus' },
        { id: 419, name: 'Toroslar' },
        { id: 420, name: 'Yenişehir' }
    ],
    34: [
        { id: 421, name: 'Adalar' },
        { id: 422, name: 'Arnavutköy' },
        { id: 423, name: 'Ataşehir' },
        { id: 424, name: 'Avcılar' },
        { id: 425, name: 'Bağcılar' },
        { id: 426, name: 'Bahçelievler' },
        { id: 427, name: 'Bakırköy' },
        { id: 428, name: 'Başakşehir' },
        { id: 429, name: 'Bayrampaşa' },
        { id: 430, name: 'Beşiktaş' },
        { id: 431, name: 'Beykoz' },
        { id: 432, name: 'Beylikdüzü' },
        { id: 433, name: 'Beyoğlu' },
        { id: 434, name: 'Büyükçekmece' },
        { id: 435, name: 'Çatalca' },
        { id: 436, name: 'Çekmeköy' },
        { id: 437, name: 'Esenler' },
        { id: 438, name: 'Esenyurt' },
        { id: 439, name: 'Eyüpsultan' },
        { id: 440, name: 'Fatih' },
        { id: 441, name: 'Gaziosmanpaşa' },
        { id: 442, name: 'Güngören' },
        { id: 443, name: 'Kadıköy' },
        { id: 444, name: 'Kağıthane' },
        { id: 445, name: 'Kartal' },
        { id: 446, name: 'Küçükçekmece' },
        { id: 447, name: 'Maltepe' },
        { id: 448, name: 'Pendik' },
        { id: 449, name: 'Sancaktepe' },
        { id: 450, name: 'Sarıyer' },
        { id: 451, name: 'Silivri' },
        { id: 452, name: 'Sultanbeyli' },
        { id: 453, name: 'Sultangazi' },
        { id: 454, name: 'Şile' },
        { id: 455, name: 'Şişli' },
        { id: 456, name: 'Tuzla' },
        { id: 457, name: 'Ümraniye' },
        { id: 458, name: 'Üsküdar' },
        { id: 459, name: 'Zeytinburnu' }
    ],
    35: [
        { id: 460, name: 'Aliağa' },
        { id: 461, name: 'Balçova' },
        { id: 462, name: 'Bayındır' },
        { id: 463, name: 'Bayraklı' },
        { id: 464, name: 'Bergama' },
        { id: 465, name: 'Beydağ' },
        { id: 466, name: 'Bornova' },
        { id: 467, name: 'Buca' },
        { id: 468, name: 'Çeşme' },
        { id: 469, name: 'Çiğli' },
        { id: 470, name: 'Dikili' },
        { id: 471, name: 'Foça' },
        { id: 472, name: 'Gaziemir' },
        { id: 473, name: 'Güzelbahçe' },
        { id: 474, name: 'Karabağlar' },
        { id: 475, name: 'Karaburun' },
        { id: 476, name: 'Karşıyaka' },
        { id: 477, name: 'Kemalpaşa' },
        { id: 478, name: 'Kınık' },
        { id: 479, name: 'Kiraz' },
        { id: 480, name: 'Konak' },
        { id: 481, name: 'Menderes' },
        { id: 482, name: 'Menemen' },
        { id: 483, name: 'Narlıdere' },
        { id: 484, name: 'Ödemiş' },
        { id: 485, name: 'Seferihisar' },
        { id: 486, name: 'Selçuk' },
        { id: 487, name: 'Tire' },
        { id: 488, name: 'Torbalı' },
        { id: 489, name: 'Urla' }
    ],
    36: [
        { id: 490, name: 'Akyaka' },
        { id: 491, name: 'Arpaçay' },
        { id: 492, name: 'Digor' },
        { id: 493, name: 'Kağızman' },
        { id: 494, name: 'Merkez' },
        { id: 495, name: 'Sarıkamış' },
        { id: 496, name: 'Selim' },
        { id: 497, name: 'Susuz' }
    ],
    37: [
        { id: 498, name: 'Abana' },
        { id: 499, name: 'Ağlı' },
        { id: 500, name: 'Araç' },
        { id: 501, name: 'Azdavay' },
        { id: 502, name: 'Bozkurt' },
        { id: 503, name: 'Cide' },
        { id: 504, name: 'Çatalzeytin' },
        { id: 505, name: 'Daday' },
        { id: 506, name: 'Devrekani' },
        { id: 507, name: 'Doğanyurt' },
        { id: 508, name: 'Hanönü' },
        { id: 509, name: 'İhsangazi' },
        { id: 510, name: 'İnebolu' },
        { id: 511, name: 'Küre' },
        { id: 512, name: 'Merkez' },
        { id: 513, name: 'Pınarbaşı' },
        { id: 514, name: 'Seydiler' },
        { id: 515, name: 'Şenpazar' },
        { id: 516, name: 'Taşköprü' },
        { id: 517, name: 'Tosya' }
    ],
    38: [
        { id: 518, name: 'Akkışla' },
        { id: 519, name: 'Bünyan' },
        { id: 520, name: 'Develi' },
        { id: 521, name: 'Felahiye' },
        { id: 522, name: 'Hacılar' },
        { id: 523, name: 'İncesu' },
        { id: 524, name: 'Kocasinan' },
        { id: 525, name: 'Melikgazi' },
        { id: 526, name: 'Özvatan' },
        { id: 527, name: 'Pınarbaşı' },
        { id: 528, name: 'Sarıoğlan' },
        { id: 529, name: 'Sarız' },
        { id: 530, name: 'Talas' },
        { id: 531, name: 'Tomarza' },
        { id: 532, name: 'Yahyalı' },
        { id: 533, name: 'Yeşilhisar' }
    ],
    39: [
        { id: 534, name: 'Babaeski' },
        { id: 535, name: 'Demirköy' },
        { id: 536, name: 'Kofçaz' },
        { id: 537, name: 'Lüleburgaz' },
        { id: 538, name: 'Merkez' },
        { id: 539, name: 'Pehlivanköy' },
        { id: 540, name: 'Pınarhisar' },
        { id: 541, name: 'Vize' }
    ],
    40: [
        { id: 542, name: 'Akçakent' },
        { id: 543, name: 'Akpınar' },
        { id: 544, name: 'Boztepe' },
        { id: 545, name: 'Çiçekdağı' },
        { id: 546, name: 'Kaman' },
        { id: 547, name: 'Merkez' },
        { id: 548, name: 'Mucur' }
    ],
    41: [
        { id: 549, name: 'Başiskele' },
        { id: 550, name: 'Çayırova' },
        { id: 551, name: 'Darıca' },
        { id: 552, name: 'Derince' },
        { id: 553, name: 'Dilovası' },
        { id: 554, name: 'Gebze' },
        { id: 555, name: 'Gölcük' },
        { id: 556, name: 'İzmit' },
        { id: 557, name: 'Kandıra' },
        { id: 558, name: 'Karamürsel' },
        { id: 559, name: 'Kartepe' },
        { id: 560, name: 'Körfez' }
    ],
    42: [
        { id: 561, name: 'Ahırlı' },
        { id: 562, name: 'Akören' },
        { id: 563, name: 'Akşehir' },
        { id: 564, name: 'Altınekin' },
        { id: 565, name: 'Beyşehir' },
        { id: 566, name: 'Bozkır' },
        { id: 567, name: 'Cihanbeyli' },
        { id: 568, name: 'Çeltik' },
        { id: 569, name: 'Çumra' },
        { id: 570, name: 'Derbent' },
        { id: 571, name: 'Derebucak' },
        { id: 572, name: 'Doğanhisar' },
        { id: 573, name: 'Emirgazi' },
        { id: 574, name: 'Ereğli' },
        { id: 575, name: 'Güneysınır' },
        { id: 576, name: 'Hadim' },
        { id: 577, name: 'Halkapınar' },
        { id: 578, name: 'Hüyük' },
        { id: 579, name: 'Ilgın' },
        { id: 580, name: 'Kadınhanı' },
        { id: 581, name: 'Karapınar' },
        { id: 582, name: 'Karatay' },
        { id: 583, name: 'Kulu' },
        { id: 584, name: 'Meram' },
        { id: 585, name: 'Sarayönü' },
        { id: 586, name: 'Selçuklu' },
        { id: 587, name: 'Seydişehir' },
        { id: 588, name: 'Taşkent' },
        { id: 589, name: 'Tuzlukçu' },
        { id: 590, name: 'Yalıhüyük' },
        { id: 591, name: 'Yunak' }
    ],
    43: [
        { id: 592, name: 'Altıntaş' },
        { id: 593, name: 'Aslanapa' },
        { id: 594, name: 'Çavdarhisar' },
        { id: 595, name: 'Domaniç' },
        { id: 596, name: 'Dumlupınar' },
        { id: 597, name: 'Emet' },
        { id: 598, name: 'Gediz' },
        { id: 599, name: 'Hisarcık' },
        { id: 600, name: 'Merkez' },
        { id: 601, name: 'Pazarlar' },
        { id: 602, name: 'Simav' },
        { id: 603, name: 'Şaphane' },
        { id: 604, name: 'Tavşanlı' }
    ],
    44: [
        { id: 605, name: 'Akçadağ' },
        { id: 606, name: 'Arapgir' },
        { id: 607, name: 'Arguvan' },
        { id: 608, name: 'Battalgazi' },
        { id: 609, name: 'Darende' },
        { id: 610, name: 'Doğanşehir' },
        { id: 611, name: 'Doğanyol' },
        { id: 612, name: 'Hekimhan' },
        { id: 613, name: 'Kale' },
        { id: 614, name: 'Kuluncak' },
        { id: 615, name: 'Pütürge' },
        { id: 616, name: 'Yazıhan' },
        { id: 617, name: 'Yeşilyurt' }
    ],
    45: [
        { id: 618, name: 'Ahmetli' },
        { id: 619, name: 'Akhisar' },
        { id: 620, name: 'Alaşehir' },
        { id: 621, name: 'Demirci' },
        { id: 622, name: 'Gölmarmara' },
        { id: 623, name: 'Gördes' },
        { id: 624, name: 'Kırkağaç' },
        { id: 625, name: 'Köprübaşı' },
        { id: 626, name: 'Kula' },
        { id: 627, name: 'Salihli' },
        { id: 628, name: 'Sarıgöl' },
        { id: 629, name: 'Saruhanlı' },
        { id: 630, name: 'Selendi' },
        { id: 631, name: 'Soma' },
        { id: 632, name: 'Şehzadeler' },
        { id: 633, name: 'Turgutlu' },
        { id: 634, name: 'Yunusemre' }
    ],
    46: [
        { id: 635, name: 'Afşin' },
        { id: 636, name: 'Andırın' },
        { id: 637, name: 'Çağlayancerit' },
        { id: 638, name: 'Dulkadiroğlu' },
        { id: 639, name: 'Ekinözü' },
        { id: 640, name: 'Elbistan' },
        { id: 641, name: 'Göksun' },
        { id: 642, name: 'Nurhak' },
        { id: 643, name: 'Onikişubat' },
        { id: 644, name: 'Pazarcık' },
        { id: 645, name: 'Türkoğlu' }
    ],
    47: [
        { id: 646, name: 'Artuklu' },
        { id: 647, name: 'Dargeçit' },
        { id: 648, name: 'Derik' },
        { id: 649, name: 'Kızıltepe' },
        { id: 650, name: 'Mazıdağı' },
        { id: 651, name: 'Midyat' },
        { id: 652, name: 'Nusaybin' },
        { id: 653, name: 'Ömerli' },
        { id: 654, name: 'Savur' },
        { id: 655, name: 'Yeşilli' }
    ],
    48: [
        { id: 656, name: 'Bodrum' },
        { id: 657, name: 'Dalaman' },
        { id: 658, name: 'Datça' },
        { id: 659, name: 'Fethiye' },
        { id: 660, name: 'Kavaklıdere' },
        { id: 661, name: 'Köyceğiz' },
        { id: 662, name: 'Marmaris' },
        { id: 663, name: 'Menteşe' },
        { id: 664, name: 'Milas' },
        { id: 665, name: 'Ortaca' },
        { id: 666, name: 'Seydikemer' },
        { id: 667, name: 'Ula' },
        { id: 668, name: 'Yatağan' }
    ],
    49: [
        { id: 669, name: 'Bulanık' },
        { id: 670, name: 'Hasköy' },
        { id: 671, name: 'Korkut' },
        { id: 672, name: 'Malazgirt' },
        { id: 673, name: 'Merkez' },
        { id: 674, name: 'Varto' }
    ],
    50: [
        { id: 675, name: 'Acıgöl' },
        { id: 676, name: 'Avanos' },
        { id: 677, name: 'Derinkuyu' },
        { id: 678, name: 'Gülşehir' },
        { id: 679, name: 'Hacıbektaş' },
        { id: 680, name: 'Kozaklı' },
        { id: 681, name: 'Merkez' },
        { id: 682, name: 'Ürgüp' }
    ],
    51: [
        { id: 683, name: 'Altunhisar' },
        { id: 684, name: 'Bor' },
        { id: 685, name: 'Çamardı' },
        { id: 686, name: 'Çiftlik' },
        { id: 687, name: 'Merkez' },
        { id: 688, name: 'Ulukışla' }
    ],
    52: [
        { id: 689, name: 'Akkuş' },
        { id: 690, name: 'Altınordu' },
        { id: 691, name: 'Aybastı' },
        { id: 692, name: 'Çamaş' },
        { id: 693, name: 'Çatalpınar' },
        { id: 694, name: 'Çaybaşı' },
        { id: 695, name: 'Fatsa' },
        { id: 696, name: 'Gölköy' },
        { id: 697, name: 'Gülyalı' },
        { id: 698, name: 'Gürgentepe' },
        { id: 699, name: 'İkizce' },
        { id: 700, name: 'Kabadüz' },
        { id: 701, name: 'Kabataş' },
        { id: 702, name: 'Korgan' },
        { id: 703, name: 'Kumru' },
        { id: 704, name: 'Mesudiye' },
        { id: 705, name: 'Perşembe' },
        { id: 706, name: 'Ulubey' },
        { id: 707, name: 'Ünye' }
    ],
    53: [
        { id: 708, name: 'Ardeşen' },
        { id: 709, name: 'Çamlıhemşin' },
        { id: 710, name: 'Çayeli' },
        { id: 711, name: 'Derepazarı' },
        { id: 712, name: 'Fındıklı' },
        { id: 713, name: 'Güneysu' },
        { id: 714, name: 'Hemşin' },
        { id: 715, name: 'İkizdere' },
        { id: 716, name: 'İyidere' },
        { id: 717, name: 'Kalkandere' },
        { id: 718, name: 'Merkez' },
        { id: 719, name: 'Pazar' }
    ],
    54: [
        { id: 720, name: 'Adapazarı' },
        { id: 721, name: 'Akyazı' },
        { id: 722, name: 'Arifiye' },
        { id: 723, name: 'Erenler' },
        { id: 724, name: 'Ferizli' },
        { id: 725, name: 'Geyve' },
        { id: 726, name: 'Hendek' },
        { id: 727, name: 'Karapürçek' },
        { id: 728, name: 'Karasu' },
        { id: 729, name: 'Kaynarca' },
        { id: 730, name: 'Kocaali' },
        { id: 731, name: 'Pamukova' },
        { id: 732, name: 'Sapanca' },
        { id: 733, name: 'Serdivan' },
        { id: 734, name: 'Söğütlü' },
        { id: 735, name: 'Taraklı' }
    ],
    55: [
        { id: 736, name: '19 Mayıs' },
        { id: 737, name: 'Alaçam' },
        { id: 738, name: 'Asarcık' },
        { id: 739, name: 'Atakum' },
        { id: 740, name: 'Ayvacık' },
        { id: 741, name: 'Bafra' },
        { id: 742, name: 'Canik' },
        { id: 743, name: 'Çarşamba' },
        { id: 744, name: 'Havza' },
        { id: 745, name: 'İlkadım' },
        { id: 746, name: 'Kavak' },
        { id: 747, name: 'Ladik' },
        { id: 748, name: 'Salıpazarı' },
        { id: 749, name: 'Tekkeköy' },
        { id: 750, name: 'Terme' },
        { id: 751, name: 'Vezirköprü' },
        { id: 752, name: 'Yakakent' }
    ],
    56: [
        { id: 753, name: 'Baykan' },
        { id: 754, name: 'Eruh' },
        { id: 755, name: 'Kurtalan' },
        { id: 756, name: 'Merkez' },
        { id: 757, name: 'Pervari' },
        { id: 758, name: 'Şirvan' },
        { id: 759, name: 'Tillo' }
    ],
    57: [
        { id: 760, name: 'Ayancık' },
        { id: 761, name: 'Boyabat' },
        { id: 762, name: 'Dikmen' },
        { id: 763, name: 'Durağan' },
        { id: 764, name: 'Erfelek' },
        { id: 765, name: 'Gerze' },
        { id: 766, name: 'Merkez' },
        { id: 767, name: 'Saraydüzü' },
        { id: 768, name: 'Türkeli' }
    ],
    58: [
        { id: 769, name: 'Akıncılar' },
        { id: 770, name: 'Altınyayla' },
        { id: 771, name: 'Divriği' },
        { id: 772, name: 'Doğanşar' },
        { id: 773, name: 'Gemerek' },
        { id: 774, name: 'Gölova' },
        { id: 775, name: 'Gürün' },
        { id: 776, name: 'Hafik' },
        { id: 777, name: 'İmranlı' },
        { id: 778, name: 'Kangal' },
        { id: 779, name: 'Koyulhisar' },
        { id: 780, name: 'Merkez' },
        { id: 781, name: 'Suşehri' },
        { id: 782, name: 'Şarkışla' },
        { id: 783, name: 'Ulaş' },
        { id: 784, name: 'Yıldızeli' },
        { id: 785, name: 'Zara' }
    ],
    59: [
        { id: 786, name: 'Çerkezköy' },
        { id: 787, name: 'Çorlu' },
        { id: 788, name: 'Ergene' },
        { id: 789, name: 'Hayrabolu' },
        { id: 790, name: 'Kapaklı' },
        { id: 791, name: 'Malkara' },
        { id: 792, name: 'Marmaraereğlisi' },
        { id: 793, name: 'Muratlı' },
        { id: 794, name: 'Saray' },
        { id: 795, name: 'Süleymanpaşa' },
        { id: 796, name: 'Şarköy' }
    ],
    60: [
        { id: 797, name: 'Almus' },
        { id: 798, name: 'Artova' },
        { id: 799, name: 'Başçiftlik' },
        { id: 800, name: 'Erbaa' },
        { id: 801, name: 'Merkez' },
        { id: 802, name: 'Niksar' },
        { id: 803, name: 'Pazar' },
        { id: 804, name: 'Reşadiye' },
        { id: 805, name: 'Sulusaray' },
        { id: 806, name: 'Turhal' },
        { id: 807, name: 'Yeşilyurt' },
        { id: 808, name: 'Zile' }
    ],
    61: [
        { id: 809, name: 'Akçaabat' },
        { id: 810, name: 'Araklı' },
        { id: 811, name: 'Arsin' },
        { id: 812, name: 'Beşikdüzü' },
        { id: 813, name: 'Çarşıbaşı' },
        { id: 814, name: 'Çaykara' },
        { id: 815, name: 'Dernekpazarı' },
        { id: 816, name: 'Düzköy' },
        { id: 817, name: 'Hayrat' },
        { id: 818, name: 'Köprübaşı' },
        { id: 819, name: 'Maçka' },
        { id: 820, name: 'Of' },
        { id: 821, name: 'Ortahisar' },
        { id: 822, name: 'Sürmene' },
        { id: 823, name: 'Şalpazarı' },
        { id: 824, name: 'Tonya' },
        { id: 825, name: 'Vakfıkebir' },
        { id: 826, name: 'Yomra' }
    ],
    62: [
        { id: 827, name: 'Çemişgezek' },
        { id: 828, name: 'Hozat' },
        { id: 829, name: 'Mazgirt' },
        { id: 830, name: 'Merkez' },
        { id: 831, name: 'Nazımiye' },
        { id: 832, name: 'Ovacık' },
        { id: 833, name: 'Pertek' },
        { id: 834, name: 'Pülümür' }
    ],
    63: [
        { id: 835, name: 'Akçakale' },
        { id: 836, name: 'Birecik' },
        { id: 837, name: 'Bozova' },
        { id: 838, name: 'Ceylanpınar' },
        { id: 839, name: 'Eyyübiye' },
        { id: 840, name: 'Halfeti' },
        { id: 841, name: 'Haliliye' },
        { id: 842, name: 'Harran' },
        { id: 843, name: 'Hilvan' },
        { id: 844, name: 'Karaköprü' },
        { id: 845, name: 'Siverek' },
        { id: 846, name: 'Suruç' },
        { id: 847, name: 'Viranşehir' }
    ],
    64: [
        { id: 848, name: 'Banaz' },
        { id: 849, name: 'Eşme' },
        { id: 850, name: 'Karahallı' },
        { id: 851, name: 'Merkez' },
        { id: 852, name: 'Sivaslı' },
        { id: 853, name: 'Ulubey' }
    ],
    65: [
        { id: 854, name: 'Bahçesaray' },
        { id: 855, name: 'Başkale' },
        { id: 856, name: 'Çaldıran' },
        { id: 857, name: 'Çatak' },
        { id: 858, name: 'Edremit' },
        { id: 859, name: 'Erciş' },
        { id: 860, name: 'Gevaş' },
        { id: 861, name: 'Gürpınar' },
        { id: 862, name: 'İpekyolu' },
        { id: 863, name: 'Muradiye' },
        { id: 864, name: 'Özalp' },
        { id: 865, name: 'Saray' },
        { id: 866, name: 'Tuşba' }
    ],
    66: [
        { id: 867, name: 'Akdağmadeni' },
        { id: 868, name: 'Aydıncık' },
        { id: 869, name: 'Boğazlıyan' },
        { id: 870, name: 'Çandır' },
        { id: 871, name: 'Çayıralan' },
        { id: 872, name: 'Çekerek' },
        { id: 873, name: 'Kadışehri' },
        { id: 874, name: 'Merkez' },
        { id: 875, name: 'Saraykent' },
        { id: 876, name: 'Sarıkaya' },
        { id: 877, name: 'Sorgun' },
        { id: 878, name: 'Şefaatli' },
        { id: 879, name: 'Yenifakılı' },
        { id: 880, name: 'Yerköy' }
    ],
    67: [
        { id: 881, name: 'Alaplı' },
        { id: 882, name: 'Çaycuma' },
        { id: 883, name: 'Devrek' },
        { id: 884, name: 'Ereğli' },
        { id: 885, name: 'Gökçebey' },
        { id: 886, name: 'Kilimli' },
        { id: 887, name: 'Kozlu' },
        { id: 888, name: 'Merkez' }
    ],
    68: [
        { id: 889, name: 'Ağaçören' },
        { id: 890, name: 'Eskil' },
        { id: 891, name: 'Gülağaç' },
        { id: 892, name: 'Güzelyurt' },
        { id: 893, name: 'Merkez' },
        { id: 894, name: 'Ortaköy' },
        { id: 895, name: 'Sarıyahşi' },
        { id: 896, name: 'Sultanhanı' }
    ],
    69: [
        { id: 897, name: 'Aydıntepe' },
        { id: 898, name: 'Demirözü' },
        { id: 899, name: 'Merkez' }
    ],
    70: [
        { id: 900, name: 'Ayrancı' },
        { id: 901, name: 'Başyayla' },
        { id: 902, name: 'Ermenek' },
        { id: 903, name: 'Kazımkarabekir' },
        { id: 904, name: 'Merkez' },
        { id: 905, name: 'Sarıveliler' }
    ],
    71: [
        { id: 906, name: 'Bahşılı' },
        { id: 907, name: 'Balışeyh' },
        { id: 908, name: 'Çelebi' },
        { id: 909, name: 'Delice' },
        { id: 910, name: 'Karakeçili' },
        { id: 911, name: 'Keskin' },
        { id: 912, name: 'Merkez' },
        { id: 913, name: 'Sulakyurt' },
        { id: 914, name: 'Yahşihan' }
    ],
    72: [
        { id: 915, name: 'Beşiri' },
        { id: 916, name: 'Gercüş' },
        { id: 917, name: 'Hasankeyf' },
        { id: 918, name: 'Kozluk' },
        { id: 919, name: 'Merkez' },
        { id: 920, name: 'Sason' }
    ],
    73: [
        { id: 921, name: 'Beytüşşebap' },
        { id: 922, name: 'Cizre' },
        { id: 923, name: 'Güçlükonak' },
        { id: 924, name: 'İdil' },
        { id: 925, name: 'Merkez' },
        { id: 926, name: 'Silopi' },
        { id: 927, name: 'Uludere' }
    ],
    74: [
        { id: 928, name: 'Amasra' },
        { id: 929, name: 'Kurucaşile' },
        { id: 930, name: 'Merkez' },
        { id: 931, name: 'Ulus' }
    ],
    75: [
        { id: 932, name: 'Çıldır' },
        { id: 933, name: 'Damal' },
        { id: 934, name: 'Göle' },
        { id: 935, name: 'Hanak' },
        { id: 936, name: 'Merkez' },
        { id: 937, name: 'Posof' }
    ],
    76: [
        { id: 938, name: 'Aralık' },
        { id: 939, name: 'Karakoyunlu' },
        { id: 940, name: 'Merkez' },
        { id: 941, name: 'Tuzluca' }
    ],
    77: [
        { id: 942, name: 'Altınova' },
        { id: 943, name: 'Armutlu' },
        { id: 944, name: 'Çiftlikköy' },
        { id: 945, name: 'Çınarcık' },
        { id: 946, name: 'Merkez' },
        { id: 947, name: 'Termal' }
    ],
    78: [
        { id: 948, name: 'Eflani' },
        { id: 949, name: 'Eskipazar' },
        { id: 950, name: 'Merkez' },
        { id: 951, name: 'Ovacık' },
        { id: 952, name: 'Safranbolu' },
        { id: 953, name: 'Yenice' }
    ],
    79: [
        { id: 954, name: 'Elbeyli' },
        { id: 955, name: 'Merkez' },
        { id: 956, name: 'Musabeyli' },
        { id: 957, name: 'Polateli' }
    ],
    80: [
        { id: 958, name: 'Bahçe' },
        { id: 959, name: 'Düziçi' },
        { id: 960, name: 'Hasanbeyli' },
        { id: 961, name: 'Kadirli' },
        { id: 962, name: 'Merkez' },
        { id: 963, name: 'Sumbas' },
        { id: 964, name: 'Toprakkale' }
    ],
    81: [
        { id: 965, name: 'Akçakoca' },
        { id: 966, name: 'Cumayeri' },
        { id: 967, name: 'Çilimli' },
        { id: 968, name: 'Gölyaka' },
        { id: 969, name: 'Gümüşova' },
        { id: 970, name: 'Kaynaşlı' },
        { id: 971, name: 'Merkez' },
        { id: 972, name: 'Yığılca' }
    ]
};

    